Add support for nix flakes
mikkun/AWKTC pull request #4
Opened 2023-09-29 20:34 UTC by MikaelFangel

This allows for users running nix flakes to run AWKTC with the command `nix run github:mikkun/AWKTC`

### Changes
 * Added the flake.nix and flake.lock files to support for running awktc using nix flakes.

2023-09-30 11:24 UTC, MikaelFangel commented
Maybe we should add a commit updating the readme with information on how to run it with flakes. If you accept the PR. (:

2023-10-03 08:20 UTC, mikkun requested changes
:pray: I have reviewed your pull request. If the issue is fixed, I will merge it.

2023-10-03 08:20 UTC, mikkun commented on flake.nix
> +  flake-utils.lib.eachDefaultSystem (system: let
![must](https://img.shields.io/badge/review-must-red.svg)
The default values of `defaultSystems` are `["x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin"]`, so when I executed `nix run` on my 32-bit Linux system, I encountered the following error:

```console
$ nix run
error: flake 'git+file:///home/mitsuhisa/Git/mikkun/AWKTC' does not provide attribute 'apps.i686-linux.default', 'defaultApp.i686-linux', 'packages.i686-linux.default' or 'defaultPackage.i686-linux'
```

Therefore, please modify so that `nix run` can be used on systems that are not in the list of `defaultSystems`.

2023-10-03 19:35 UTC, MikaelFangel commented on flake.nix
> +  flake-utils.lib.eachDefaultSystem (system: let
I've expanded it to allSystems.

2023-10-03 19:36 UTC, MikaelFangel commented
@mikkun I've changed the set to all systems, so it should work on your architecture now.

2023-10-04 15:00 UTC, mikkun approved these changes
:star2: I have confirmed the changes. As the issue has been fixed, I will merge the pull request and update the `README.md`.

2023-10-04 15:00 UTC, mikkun commented on flake.nix
> +  flake-utils.lib.eachSystem flake-utils.lib.allSystems (system: let
![suggestion](https://img.shields.io/badge/review-suggestion-teal.svg)
Thank you for the corrections. I have confirmed that `nix run` is working correctly. By the way, I'm considering shortening `flake-utils.lib.eachSystem flake-utils.lib.allSystems` to `with flake-utils.lib; eachSystem allSystems`. What do you think?

See also: <https://nixos.wiki/wiki/Overview_of_the_Nix_Language#with_statement>

2023-10-04 15:26 UTC, MikaelFangel commented
Thank you 🙏🏻

2023-10-04 15:59 UTC, MikaelFangel commented on flake.nix
> +  flake-utils.lib.eachSystem flake-utils.lib.allSystems (system: let
Hm, I think it's a valid approach. Chose not to do it because it was only two references (:

2023-10-05 02:30 UTC, mikkun commented on flake.nix
> +  flake-utils.lib.eachSystem flake-utils.lib.allSystems (system: let
:pray: I would prefer to prioritize avoiding code duplication over emphasizing namespace, so please change it to `with flake-utils.lib; eachSystem allSystems`.

2023-10-05 13:36 UTC, MikaelFangel commented on flake.nix
> +  flake-utils.lib.eachSystem flake-utils.lib.allSystems (system: let
Have pushed a commit, changing it now :octocat:

2023-10-06 14:45 UTC, merged